### ISSUE TITLE
Domain dump fails on Server 2019

### ISSUE THREAD

**Issue by Invoke-Mimikatz** [G0ldenGunSec/SharpSecDump#1]
Hey there! I really like the idea for this tool! I tried to get it working in my lab but was unable to dump domain credentials as expected.

I compiled the program as-is using Visual Studio and tried to run it in the context of a Domain Admin (no credentials specified) from a Windows 10 Workstation. All AV was disabled. These are the results:

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/57604669/91886786-d8184300-ec57-11ea-9e50-5e4f6edcd05c.png">

As you can see, something went wrong with the domain dump, and no domain account hashes were printed.

To sanity check myself, I ran secretsdump.py from a Kali box, and was able to recover domain account hashes no problem:

<img width="948" alt="image" src="https://user-images.githubusercontent.com/57604669/91887069-4a892300-ec58-11ea-8872-be97782e0bfb.png">

The target Domain Controller is Server 2019 version 1809:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/57604669/91887177-6ab8e200-ec58-11ea-9429-5ee8093cb5db.png">

**Comment by G0ldenGunSec** [comment]
The crash is not expected (and I'll push a change to fix that), but ntds.dit functionality is not yet implemented, as that relies much more heavily on direct RPC calls and a bunch of functionality I have not yet coded.  Planning to eventually get that functionality added in, but in the meantime this project does have dcsync functionality: https://github.com/b4rtik/SharpKatz

**Comment by Invoke-Mimikatz** [comment]
My mistake! Didn't realize DCSync functionality was not included. Feel free to close.
